apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.blueName }}
  labels:
    app: {{ .Values.image.name }}
    service: {{ .Values.image.name }}
    slot: blue
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  type: ClusterIP 
  selector:
    app: {{ .Values.image.name }}
    version: {{ .Values.service.blueVersion }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.greenName }}
  labels:
    app: {{ .Values.image.name }}
    service: {{ .Values.image.name }}
    slot: green
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  type: ClusterIP 
  selector:
    app: {{ .Values.image.name }}
    version: {{ .Values.service.greenVersion }}