---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service-weights: | 
      {{ .Values.service.blueName }}: {{ .Values.service.blueWeight }}
      {{ .Values.service.greenName }}: {{ .Values.service.greenWeight }}
  name: {{ .Values.service.blueName }}
spec:
  rules:
  - http: 
      paths: 
      - backend:
          serviceName: {{ .Values.service.blueName }}
          servicePort: {{ .Values.service.port }}
        path: /
      - backend:
          serviceName: {{ .Values.service.greenName }} 
          servicePort: {{ .Values.service.port }}
        path: /
