blueReplicaCount: 2
greenReplicaCount: 1

image:
  repository: bjd145
  name: whatos
  blueTag: "1.0"
  greenTag: "2.0"

service:
  port: 8081
  blueName: whatos-v1
  blueWeight: 80%
  blueVersion: v1
  greenName: whatos-v2
  greenWeight: 20%
  greenVersion: v2

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
