trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - pipelines/*
    - deploy/*

variables:
    dockerid:   'bjd145'
    imageName:  'bjd145/whatos'

stages:
- stage: builds
  jobs: 
  - job: 'Build_And_Push'
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
         
    #- bash: |
    #    echo $(dockerPassword) | docker login -u $(dockerId) --password-stdin
    #  displayName: Log into Docker

    #- bash: |
    #    cd src
    #    docker build -t $(imageName):1.0 .
    #    docker push $(imageName):1.0
    #  displayName: Build and Push Container v1.0

    #- bash: |
    #    cd src
    #    docker build -t $(imageName):2.0 .
    #    docker push $(imageName):2.0
    #  displayName: Build and Push Container v2.0

    - task: CopyFiles@2
      inputs:
        SourceFolder: deploy
        TargetFolder: '$(build.artifactstagingdirectory)'
      displayName: Copy Artifacts  

    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts 

- stage: deploy_10_percent
  jobs:
  - deployment: 'Deploy_To_AKS'
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'AKS.whatosapi'
    strategy:
      runOnce:
      
        preDeploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(System.DefaultWorkingDirectory)/'
          - task: HelmInstaller@0
            displayName: 'Install Helm 3.0.2'
            inputs:
              helmVersionToInstall: '3.0.2'

        deploy:
          steps:
          - task: HelmDeploy@0
            displayName: 'helm upgrade'
            inputs:
              azureSubscription: 'BJD_APP02_Subscription'
              azureResourceGroup: 'DevSub02_K8S01_RG'
              kubernetesCluster: bjdk8s01
              namespace: whatosapi
              command: upgrade
              chartType: filepath
              chartPath: './drop/helm'
              releaseName: whatosapi
              install: true
              overrideValues: 'service.greenWeight=10%,service.blueWeight=90%,greenReplicaCount=1,blueReplicaCount=3 '
              valueFile: './drop/helm/values.yaml'

          - task: ManualIntervention@8
            inputs:
              instructions: 'Please validate environment'

        on:
          failure:         
          steps:
            - task: HelmDeploy@0
              displayName: 'helm rollback'
              inputs:
                azureSubscription: 'BJD_APP02_Subscription'
                azureResourceGroup: 'DevSub02_K8S01_RG'
                kubernetesCluster: bjdk8s01
                namespace: whatosapi
                command: rollback
                arguments: 'whatosapi 0'